# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1536545e872d759ca9d658a8804e051e3c99f2ae3df0d34219098f31b5e5a1556a85174eb6b7f83d30af2e1c1107eab04d01488181e89811a020bd086c0fee69

test:
  secret_key_base: a4e5917131d957934d353adc513b2856f98e0f4825942a41c3d6343a9b2a93cbfb7a9b1d2c98af5f0398e2be7470ea36882131b5bb068d66276ee17d9260b146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
